export const TRANSACTION_RESET = 'TRANSACTION_RESET';
export const TRANSACTION_SET_AMOUNT = 'TRANSACTION_SET_AMOUNT';
export const TRANSACTION_ADD_AMOUNT = 'TRANSACTION_ADD_AMOUNT';
export const TRANSACTION_SET_TYPE = 'TRANSACTION_SET_TYPE';
