export const TRANSACTIONS_REMOVE = 'TRANSACTIONS_REMOVE';
export const TRANSACTIONS_UPDATE = 'TRANSACTIONS_UPDATE';
export const TRANSACTIONS_SHOW = 'TRANSACTIONS_SHOW';
export const TRANSACTIONS_HIDE = 'TRANSACTIONS_HIDE';
